### ISSUE TITLE
How to debug gulp tasks?

### ISSUE THREAD

**Issue by marcellodesales** [koemei/gulp-node-inspector#11]
Installed and updated my Gulpfile...

```js
$ cat Gulpfile.js 
"use strict";

var gulp = require('./build/gulp')({
  srcPaths: ["src/**/*.js", "build/**/*.js", "tasks/**/*.js", "utils/**/*.js"]
});

var nodeInspector = require("gulp-node-inspector");
 
gulp.task("debug", function() {
  gulp.src([]).pipe(nodeInspector());
});
```

I ran the `gulp debug` command and went to my chrome... 

![screen shot 2015-06-16 at 9 59 46 am](https://cloud.githubusercontent.com/assets/131457/8189067/8a7c5888-140e-11e5-9ffb-36e13e5e5340.png)

All screens were empty, although it connected to the debug URL... 

![screen shot 2015-06-16 at 9 59 16 am](https://cloud.githubusercontent.com/assets/131457/8189060/838bd210-140e-11e5-817f-8d7a90a0bf6c.png)

* How can I debug gulp execution?

I opened another terminal screen and ran gulp commands, but nothing happened.
I also tried to run "gulp" from the browser terminal and nothing happened...

**Comment by vesparny** [comment]
could you provide some context?

What do you mean with
>I opened another terminal screen and ran gulp commands, but nothing happened.

**Comment by marcellodesales** [comment]
Well, I was under the impression I could run `gulp TASK` and put break-points in the inspector...

**Comment by marcellodesales** [comment]
@vesparny Do you have any comments here?

**Comment by vesparny** [comment]
this is meant to debug code, not gulp tasks

**Comment by marcellodesales** [comment]
:) isn't it spawn by gulp??? Couldn't I use this to debug Tests run by Gulp? :) You confused me :(

**Comment by vesparny** [comment]
This plugin is meant to debug a running node process, not for debugging gulp tasks.

you need to launch with the debug option:

```shell
node server.js --debug=5082
```

then from a gulp task

```js
gulp.task('node-inspector', function () {
  return gulp.src([])
    .pipe(plugins.nodeInspector({
      webPort: 8081,
      webHost: 'localhost',
      debugPort: 5082
    }));
});
```

**Comment by marcellodesales** [comment]
Ok... That makes sense now... And great! IT works!!!

HOWEVER, I needed to change the command that  I ran my server:

```
node --debug server.js
```

I think because I'm still on Node 0.10.x... The default port for debug is printed in logs...

```
$ node --debug server.js 
debugger listening on port 5858
```

So I had to adjust the settings as follows:

```js
gulp.task('node-inspector', function () {
  return gulp.src([])
    .pipe(nodeInspector({
      webPort: 8081,
      webHost: 'localhost',
      debugPort: 5858
    }));
});
```

Everything worked!!! Thanks a lot @vesparny!!!

<img width="1333" alt="screen shot 2015-07-03 at 11 05 56 am" src="https://cloud.githubusercontent.com/assets/131457/8503418/eecc876e-2173-11e5-8bb0-bae800fab5c6.png">
