### ISSUE TITLE
gulp-nodemon example

### ISSUE THREAD

**Issue by hendrikswan** [koemei/gulp-node-inspector#2]
Hi, 

This looks really promising, and what sold me is that you mention in your readme that it works well with gulp-nodemon. 

I think it'll really help me and other developers if you could give an example of configuring the task with nodemon.

**Comment by vohtaski** [comment]
I have added in the readme an example of config with nodemon:
https://github.com/koemei/gulp-node-inspector/blob/master/README.md#usage

pls let me know if it's clear enough
