### ISSUE TITLE
Hardcoded list of options in index.js

### ISSUE THREAD

**Issue by JohannesHoppe** [koemei/gulp-node-inspector#4]
Starting on line 13 you are defining a list of hardcoded command-line options. I see the benefit for "hidden", since its gets stringified. But on the other hand people might get confused since "inject", "ssl-key" and "ssl-cert" will be ignored. What’s about passing all options directly to "args" without any filtering?

Regards,
Johannes

**Comment by vohtaski** [comment]
Makes sense, could you submit a pull request pls?

**Comment by JohannesHoppe** [comment]
Of course, not a big deal at all. But I worry about issue #5 ...
