### ISSUE TITLE
Not a gulp plugin

### ISSUE THREAD

**Issue by phated** [koemei/gulp-node-inspector#5]
Doesn't follow any [guidelines](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md) of a gulp plugin.  Doesn't deal with streams.

**Comment by JohannesHoppe** [comment]
I think the plugin is already pretty useful, even without streams. The fundamental issue is the fact that it wraps something "for the sake of wrapping it". Do you think that package would bel acceptable, if it would follow all other guidelines?

**Comment by JohannesHoppe** [comment]
On the other hand, why should it ever deal with streams? Lets change the title of this issue to: "This should have a gulpfriendly keyword instead of gulpplugin"

Problem solved! :-)
