### ISSUE TITLE
Blacklisted on http://gulpjs.com/plugins/

### ISSUE THREAD

**Issue by JohannesHoppe** [koemei/gulp-node-inspector#8]
@phated blacklisted (the old version of) the plugin
https://github.com/gulpjs/plugins/commit/a6e707b784c87529f7b1dda8b5b355aaa86064a4

related to #5

**Comment by phated** [comment]
still blacklisted, just for a different reason.  There is no reason this should deal with streams, it isn't doing anything with vinyl objects.  This should just be abstracted into a generic module and label it gulpfriendly

**Comment by vesparny** [comment]
@phated I see the point. Should we rename the package name?
Or it's just sufficient to tag the module as **gulpfriendly** ?

**Comment by phated** [comment]
I think it is useful outside of gulp.  For that reason, it seems to make sense to rename it __and__ add the gulpfriendly keyword, but it is not necessary to rename.

**Comment by vesparny** [comment]
Ok thanks, I'll do it asap.

**Comment by vesparny** [comment]
@phated I added the gulpfriendly keyword, could you please remove the plugin from the blacklist?

**Comment by phated** [comment]
I've reviewed and the module still tries to act as a stream, yet it has no reason to be one.  Just make it a function that takes a callback and it is way more gulpfriendly than trying to be a stream.

**Comment by JohannesHoppe** [comment]
Ok, gulp-karma is also on backlist now, see https://github.com/gulpjs/plugins/pull/149
I used their code as a boilerplace. At least this makes sence, now.
